version: "3.4"

services:
  # server flask
  flask-app:
    build:
      context: ./server/flask
      network: host
    ports:
      - "5000"
    image: flask-app-image
    networks:
      - app-network

  # model
  model:
    build:
      context: ./server/model
      network: host
    ports:
      - "5050"
    image: model-image
    networks:
      - app-network

  # nginx load balancer
  nginx:
    image: nginx:latest
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
    ports:
      - "4000:4000"
    networks:
      - app-network

  # client reactjs
  react-app:
    build:
      context: ./client
      network: host
    depends_on:
     - flask-app
    ports:
     - "3000:3000"
    image: react-app-image
    networks:
      - app-network

networks:
  app-network:
    driver: bridge