version: "3"

services:

  # server flask
  flask-app:
    build:
      context: ./server/flask
      network: host
    ports:
      - "5005"
    image: flask-app-image
    container_name: flask-server-container
    network_mode: host
    restart: always

  # server model
  model:
    build:
      context: ./server/model
      network: host
    ports:
      - "5050"
    image: model-image
    container_name: model-server-container
    network_mode: host
    restart: always

    # client reactjs
  react-app:
    build:
      context: ./client
      network: host
    depends_on:
     - flask-app
    ports:
     - "8501:3000"
    image: react-app-image
    container_name: react-client-container
    network_mode: host
