version: "3"

services:
  # server flask
  flask-app:
    build:
      context: ./server/flask
    ports:
      - "5000"
    image: flask-app-image

  # nginx load balancer
  nginx:
    image: nginx:latest
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
    ports:
      - "4000:4000"

  # client reactjs
  react-app:
    build:
      context: ./client
    depends_on:
     - flask-app
    ports:
     - "3000:3000"
    image: react-app-image