version: "3"

services:

  # server flask
  flask-app:
    build:
      context: ./server/flask
      network: host
    ports:
      - "8084"
    image: flask-app-image
    container_name: flask-server-container
    volumes:
      - ./uploads:/app/uploads
      - ./config/:/app/config
      - ./logs/:/app/logs
    network_mode: host

  # server model
  model:
    build:
      context: ./server/model
      network: host
    ports:
      - "5050"
    image: model-image
    container_name: model-server-container
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    network_mode: host

    # client reactjs
  react-app:
    build:
      context: ./client
      network: host
    depends_on:
     - flask-app
    ports:
     - "8501:3000"
    image: react-app-image
    container_name: react-client-container
    network_mode: host

volumes:
  uploads:
  config:
  logs: