proj4:
  practice:
    - url: /proj4
      text: 'Scrabble: Exercise on a similar topic'
  external:
    - url: https://docs.python.org/3/howto/sorting.html
      text: Sorting Techniques (Python 3 documentation)
    - url: https://realpython.com/python-sets/
      text: Set Operations in Python
proj5:
  external:
    - url: https://www.linuxtopia.org/online_books/programming_books/python_programming/python_ch15s09.html
      text: Advanced Parameter Handling For Functions
    - url: https://uwpce-pythoncert.github.io/ProgrammingInPython/modules/AdvancedArgumentPassing.html
      text: Advanced Argument Passing

proj6:
  external:
    - url: https://www.pythonlikeyoumeanit.com/Module4_OOP/Special_Methods.html
      text: Special Methods in Python 
    - url: https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://wikidocs.net/82426&ved=2ahUKEwjZy5rl0IyFAxV9gf0HHTKmB0gQFnoECBQQAQ&usg=AOvVaw1TAF19WBadNSx9s1he9ben
      text: Special Methods - Practical Python Programming
proj8:
  practice:
    - url: /proj8
      text: 'Email Queue: Exercise on a similar topic'
  external:
    - url: https://realpython.com/introduction-to-python-generators/
      text: How to Use Generators and yield in Python
proj9:
  external:
    - url: https://regex.sketchengine.eu/basic-exercises.html
      text: 'Regular expression: Basic exercises'
    - url: https://www.w3resource.com/python-exercises/re/
      text: Python Regular Expression - Exercises, Practice, Solution
    - url: https://www.pythoncheatsheet.org/cheatsheet/regular-expressions
      text: Regular expressions Cheatsheet
proj10:
  external:
    - url: https://programminghistorian.org/en/lessons/manipulating-strings-in-python
      text: Manipulating Strings in Python
    - url: https://www.codecademy.com/learn/learn-python-3/modules/learn-python3-lists/cheatsheet
      text: 'Learn Python 3: Lists Cheatsheet'
proj11:
  external:
    - url: https://www.codecademy.com/learn/learn-python-3/modules/learn-python3-loops/cheatsheet
      text: 'Learn Python 3: Loops Cheatsheet'
    - url: https://pynative.com/python-if-else-and-for-loop-exercise-with-solutions/
      text: Python if else, for loop, and range() Exercises with Solutions
proj20:
  external:
    - url: https://docs.aiohttp.org/en/stable/
      text: Official documentation
    - url: https://www.twilio.com/en-us/blog/asynchronous-http-requests-in-python-with-aiohttp
      text: Asynchronous HTTP Requests in Python with aiohttp and asyncio